# -*- coding: utf-8 -*-
"""advinhacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ga5C7iB5EI9KnOs3tWDHAKptZLeV8hQW
"""

import random
import os #biblioteca para controlar o sistema

def jogar():
    def cabecalho():
        print("***********************");
        print("*** JOGO ADVINHAÇÃO ***");
        print("***********************\n");
    
    def sorteia_numero():
        # sorteia numero aleatorio de 0 a 100
        return round(random.random() * 100);

    def calcula_pontuacao(pontos, n):
        if(n == 1):
            p = pontos - 100;
        if(n == 2):
            p = pontos - 200;
        else:
            p = pontos - 333.3;
        return round(p)
    
    def numero_de_rodadas(n):
            if(n == 1):
                return 10
            if(n == 2):
                return 5;
            else:
                return 3;

    def escolhe_nivel():
        print("\n***********************");
        print("*** ESCOLHA O NÍVEL ***");
        print("***********************");
        print("\t(1) FÁCIL", "\t(2) MÉDIO", "\t(3) DIFÍCIL", sep="\n");
        print("***********************");
        op = int(input("OPÇÃO: "));
        
        while(op < 1 or op > 3):
            print("***********************\n");
            op = int(input("OPÇÃO: "));

        print("\n")    
        return op 

    cabecalho()

    pontos = 1000;
    rodadas = 1;
    nivel = escolhe_nivel();
    r = numero_de_rodadas(nivel);
    num_sorteado = sorteia_numero();

    # comandos para limpar area de execução
    # os.system("cls");
    # os.system("clear");
    print(num_sorteado)
    while(rodadas <= r):
        print("************ RODADA {} DE {} ************\n".format(rodadas, r))
        chute = int(input("DIGITE UM NÚMERO ENTRE 0 E 100: "))
        if(chute == num_sorteado):
            print("VOCÊ ACERTOU !!!")
            print("{} PONTOS".format(pontos))
            break
        elif(chute < num_sorteado):
            print("SEU CHUTE ESTÁ ABAIXO DO NÚMERO SORTEADO");
        elif(chute > num_sorteado):
            print("SEU CHUTE ESTÁ ACIMA DO NÚMERO SORTEADO");

        rodadas = rodadas + 1;
        pontos = calcula_pontuacao(pontos, nivel)
        if(rodadas > r):
            print("\nVOCÊ PERDEU !!! TENTE NOVAMENTE")
            print("{} PONTOS".format(pontos))
        print("***************************************\n");

if(__name__ == "__main__"):
	jogar();
